### ISSUE TITLE
[quickstart] Clarify how to run PlyQL against datasources with dashes

### ISSUE THREAD

**Issue by gianm** [implydata/distribution#7]
I think you need to quote them with backticks.

**Comment by vogievetsky** [comment]
Alternatively we can make PlyQL have a special parser clause for the FROM clause seeing as it is a pretty specific clause in SQL. (Right now it is just using the standard literal name). I think I like this approach better rather than leaving a note.

**Comment by gianm** [comment]
That would work too!

**Comment by vogievetsky** [comment]
https://github.com/implydata/plywood/pull/53

**Comment by vogievetsky** [comment]
This will be in the next IAP we could still put a not on 1.1.0 (and before) but maybe it is not worth the hustle.

**Comment by gianm** [comment]
Fixed in current releases.
