### ISSUE TITLE
druid.broker.cache.useCache VS druid.historical.cache.useCache

### ISSUE THREAD

**Issue by l15k4** [implydata/distribution#9]
Hey,

I've noticed that `druid.broker.cache.useCache` property is in both `broker` and `historical` configuration files. Shouldn't there be `druid.historical.cache.useCache` in the `historical` configuration? 

If it is not a mistake, what is the reason behind this naming convention? What is actually getting cached on broker and historical node?

**Comment by gianm** [comment]
This was a mistake, fixed in d7ae1a6f34f0dd8a89e914ab6f73e3669db320db. Thanks for the catch!

**Comment by l15k4** [comment]
:+1: There is one more suspicious property : 
```
druid.processing.buffer.sizeBytes=
druid.processing.numThreads=
```

are in `broker`, `historical` and `middleManager`. I have a notion of what it does in `broker` and `historical`, but have no idea what it is for in `middleManager`. Is it correct? If so, what is it for in `middleManager` ?

**Comment by gianm** [comment]
@l15k4 in the middleManager it is intended that those will get passed down to the peons, where they'll influence the processing threads and buffers of realtime tasks.

**Comment by l15k4** [comment]
@gianm Thank you, another observation is that : 
```
druid.cache.sizeInBytes
```

is present in `historical` properties only, but it is used by `broker` as well. Shouldn't it be like this?  : 
```
druid.broker.cache.sizeInBytes
druid.historical.cache.sizeInBytes
```

Otherwise it is very misleading to figure out what is actually being cached and where. 

The way I understand it is that `broker` reads `druid.cache.sizeInBytes` property to set up query cache and `historical` reads `druid.cache.sizeInBytes` property to set up segments cache.

BUT `druid.cache.sizeInBytes` being in `historical` property file only means that these to caches cannot have different size???

**Comment by l15k4** [comment]
@gianm in regards to caching, I think that these properties in `historical` : 
```
druid.segmentCache.locations=[{"path":"var/druid/segment-cache","maxSize"\:300000000000}]
druid.server.maxSize=300000000000
``` 
are not used because no matter what number I set there coordinator log is still WARNing me about : 
```
Not enough [_default_tier] servers or node capacity to assign segment
```

And `segment-cache` directory never crosses 500M : 
```
$ du -sh var/druid/segment-cache/
500M    segment-cache/
```

I cannot find where `500M` comes from.
